library('ape')
library('dclone')
library('geiger')
library('MASS')
library('phytools')
library('scales')
library('mvtnorm')

source('analyses/src/load-src.R')
source('analyses/occupancy-phylo/src/analyses.R')
source('analyses/occupancy-phylo/src/plotting.R')
source('analyses/occupancy-phylo/src/misc.R')
source('analyses/occupancy-phylo/src/prep.R')
source('analyses/occupancy-phylo/src/simulate_data.R')
source('analyses/occupancy-phylo/src/simulate_functions.R')
source('analyses/occupancy-phylo/src/bayesfactors.R')
